apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-liran
spec:
  containers:
  - image: redis:alpine
    name: redis-container
    volumeMounts:
    - mountPath: /data/redis
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}